config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    scope '(:apiv)', module: :v2,
                     defaults: { apiv: 'v2' },
                     apiv: /v1|v2/,
                     constraints: ApiConstraints.new(version: 2) do
      get 'passwords/:user', to: 'passwords#acquire'
      delete 'passwords/:user', to: 'passwords#release'
    end
  end

  scope '/foreman_passwordstate' do
    constraints(id: %r{[^/]+}) do
      resources :passwordstate_servers do
        collection do
          get 'auto_complete_search'
          post 'test_connection'
        end
        member do
          get 'folders'
          get 'password_lists'
        end
      end
    end
  end

  constraints(id: %r{[^/]+}) do
    resources :hostgroups, only: [] do
      collection do
        post 'passwordstate_server_selected'
      end
    end
    resources :hosts, only: [] do
      collection do
        post 'passwordstate_server_selected'
      end
      member do
        get 'passwordstate_passwords_tab_selected'
      end
    end
    resources :discovered_hosts, only: [] do
      collection do
        post 'passwordstate_server_selected'
      end
    end
  end
end

app/models/concerns/foreman_passwordstate/host_common_extensions.rb
# frozen_string_literal: true

module ForemanPasswordstate
  module HostCommonExtensions
    def crypt_root_pass
      return if !is_a?(Hostgroup) && passwordstate_facet

      super
    end
  end
end

app/models/concerns/foreman_passwordstate/host_managed_extensions.rb
# frozen_string_literal: true

module ForemanPasswordstate
  module HostManagedExtensions
    extend ActiveSupport::Concern

    prepended do
      include ::Orchestration::Passwordstate

      scoped_search on: :passwordstate_server_id,
                    relation: :passwordstate_facet,
                    rename: :passwordstate_server,
                    complete_value: true,
                    only_explicit: true
    end

    def ensure_passwordstate_facet(save: true, **attrs)
      return passwordstate_facet if passwordstate_facet && attrs.empty?

      attrs = passwordstate_facet.attributes.merge(attrs) if passwordstate_facet
      attrs = hostgroup.inherited_facet_attributes(Facets.registered_facets[:passwordstate_facet]).merge(attrs) if hostgroup

      if passwordstate_facet
        f = passwordstate_facet
        f.assign_attributes attrs
      else
        f = build_passwordstate_facet attrs
      end
      f.save if save && persisted?

      f
    end

    def root_pass
      return super unless passwordstate_facet
      return 'PlaceholderDuringCreation' if !persisted? || domain.nil?

      root_user = operatingsystem&.root_user || 'root'
      host_pass(root_user, password_hash: operatingsystem&.password_hash)
    rescue StandardError => e
      fullmessage = e.to_s.tr("\n", '½')
      logger.error "Failed to get root_pass for #{self} - #{e.class}: #{fullmessage}"
      Digest::SHA256.hexdigest("#{id}-PlaceholderDueToPasswordstateError")
    end

    def crypt_root_pass
      return if passwordstate?

      super
    end
  end
end

class Host::Managed::Jail < Safemode::Jail # rubocop:disable Style/ClassAndModuleChildren
  allow :host_pass
end

app/models/concerns/foreman_passwordstate/operatingsystem_extensions.rb
# frozen_string_literal: true

module ForemanPasswordstate
  module OperatingsystemExtensions
    def root_user
      if family == 'Windows'
        'Administrator'
      else
        'root'
      end
    end
  end
end

app/models/concerns/foreman_passwordstate/passwordlist_ensurance.rb
# frozen_string_literal: true

module ForemanPasswordstate
  module PasswordlistEnsurance
    extend ActiveSupport::Concern

    included do
      before_validation :ensure_passwordlist
      validate :validate_passwordlist
    end

    private

    def ensure_passwordlist
      return unless passwordstate_server
      return if passwordstate_server.api_type.to_sym == :winapi

      self.password_list_id = passwordstate_server.user.to_i
    end

    def validate_passwordlist
      return unless passwordstate_server && password_list_id

      passwordstate_server.password_lists.get(password_list_id)
    rescue Passwordstate::UnauthorizedError
      errors.add(:password_list_id, 'must be owned by the chosen Passwordstate server')
    end
  end
end

app/models/concerns/foreman_passwordstate/passwordstate_caching.rb
# frozen_string_literal: true

module ForemanPasswordstate
  module PasswordstateCaching
    extend ActiveSupport::Concern

    included do
      after_update :refresh_cache_ignoring_errors, if: proc(&:caching_enabled?)
    end

    def caching_enabled?
      true
    end

    def refresh_cache_ignoring_errors
      refresh_cache
      true
    end

    def refresh_cache
      cache.refresh
    end

    private

    def cache
      @cache ||= ForemanPasswordstate::PasswordstateCache.new(self)
    end
  end
end

app/models/foreman_passwordstate/passwordstate_cache.rb
# frozen_string_literal: true

module ForemanPasswordstate
  class PasswordstateCache
    include Singleton

    # create a private instance of MemoryStore
    def initialize
      @memory_store = ActiveSupport::Cache::MemoryStore.new
    end

    # this will allow our MemoryCache to be called just like Rails.cache
    # every method passed to it will be passed to our MemoryStore
    def method_missing(method, *args, &block)
      if respond_to_missing?(method)
        @memory_store.send(method, *args, &block)
      else
        super
      end
    end

    def respond_to_missing?(method, *)
      @memory_store.respond_to?(method)
    end
  end
end

app/models/foreman_passwordstate/passwordstate_facet.rb
module ForemanPasswordstate
  class PasswordstateFacet < ApplicationRecord
    include Facets::HostgroupFacet
    include Facets::Base

    belongs_to :passwordstate_server,
               class_name: '::PasswordstateServer',
               inverse_of: :passwordstate_facets

    validates_lengths_from_database

    # validates :host, presence: true, allow_blank: false
    validates :passwordstate_server, presence: true, allow_blank: false

    before_save :temporary_hack

    def password_list
      return nil unless password_list_id

      passwordstate_server.password_lists.get(password_list_id)
    end

    def temporary_hack
      logger.debug "TODO: Fix this properly."

      hostgroup_id = nil unless host_id.nil?
    end
  end
end

app/models/foreman_passwordstate/passwordstate_host_facet.rb
# frozen_string_literal: true

module ForemanPasswordstate
  class PasswordstateHostFacet < ApplicationRecord
    include Facets::Base
    include ForemanPasswordstate::PasswordlistEnsurance

    belongs_to :passwordstate_server,
               class_name: '::PasswordstateServer',
               inverse_of: :passwordstate_host_facets

    validates_lengths_from_database

    validates :host, presence: true, allow_blank: false
    validates :passwordstate_server, presence: true, allow_blank: false
    validates :password_list_id, presence: true, allow_blank: false

    def password_list(**query)
      passwordstate_server.password_lists.get(password_list_id, **query)
    end

    # FOREMAN-37043
    def self.inherited_attributes(hostgroup, facet_attributes)
      (facet_attributes || {}).merge(super) { |_, left, right| left || right }
    end
  end
end

app/models/foreman_passwordstate/passwordstate_hostgroup_facet.rb
# frozen_string_literal: true

module ForemanPasswordstate
  class PasswordstateHostgroupFacet < ApplicationRecord
    include Facets::HostgroupFacet
    include ForemanPasswordstate::PasswordlistEnsurance

    belongs_to :passwordstate_server,
               class_name: '::PasswordstateServer',
               inverse_of: :passwordstate_hostgroup_facets

    validates_lengths_from_database

    validates :hostgroup, presence: true, allow_blank: false
    validates :passwordstate_server, presence: true, allow_blank: false

    class << self
      def attributes_to_inherit
        @attributes_to_inherit ||= attribute_names - %w[id created_at updated_at hostgroup_id]
      end
    end

    inherit_attributes(*%w[passwordstate_server_id password_list_id])

    def password_list(**query)
      return nil unless password_list_id

      passwordstate_server.password_lists.get(password_list_id, **query)
    end
  end
end

app/controllers/concerns/foreman_passwordstate/find_host_by_client_cert.rb
# frozen_string_literal: true

module ForemanPasswordstate
  module FindHostByClientCert
    extend ActiveSupport::Concern

    module ClassMethods
      def authorize_host_by_client_cert(actions, _options = {})
        skip_before_action :require_login, only: actions, raise: false
        skip_before_action :authorize, only: actions
        skip_before_action :verify_authenticity_token, only: actions
        skip_before_action :set_taxonomy, only: actions, raise: false
        skip_before_action :session_expiry, :update_activity_time, only: actions
        before_action(only: actions) { require_client_cert_or_login }
        attr_reader :detected_host
      end
    end

    private

    # Permits Hosts authorized by their client cert
    # or a user with permission
    def require_client_cert_or_login
      @detected_host = find_host_by_client_cert

      if detected_host
        set_admin_user
        return true
      end

      require_login
      unless User.current
        render_error 'unauthorized', status: :unauthorized unless performed? && api_request?
        return false
      end
      authorize
    end

    def find_host_by_client_cert
      hostname = get_client_cert_hostname

      return unless hostname

      host ||= Host::Base.find_by(certname: hostname) ||
               Host::Base.find_by(name: hostname)
      logger.info { "Found Host #{host} by client cert #{hostname}" } if host
      host
    end

    def get_client_cert_hostname
      verify = request.env[Setting[:ssl_client_verify_env]]
      unless verify == 'SUCCESS'
        logger.info { "Client certificate is invalid: #{verify}" }
        return
      end

      dn = request.env[Setting[:ssl_client_dn_env]]
      return unless dn && dn =~ %r{CN=([^\s/,]+)}i

      hostname = Regexp.last_match(1).downcase
      logger.debug "Extracted hostname '#{hostname}' from client certificate."
      hostname
    end
  end
end

app/controllers/concerns/foreman_passwordstate/hostgroups_controller_extensions.rb
# frozen_string_literal: true

module ForemanPasswordstate
  module HostgroupsControllerExtensions
    def update
      super

      return unless hostgroup_params.dig(:passwordstate_facet_attributes, :passwordstate_server_id).empty?
      return unless @hostgroup.passwordstate_facet

      @hostgroup.passwordstate_facet.destroy
    end

    def passwordstate_server_selected
      object = @hostgroup || item_object
      passwordstate_facet = object.passwordstate_facet || object.build_passwordstate_facet
      passwordstate_facet.passwordstate_server_id ||= hostgroup_params.dig(:passwordstate_facet_attributes, :passwordstate_server_id).empty?

      render partial: 'foreman_passwordstate/host_password_choice', locals: { item: passwordstate_facet }
    end
  end
end

app/controllers/concerns/foreman_passwordstate/hosts_controller_extensions.rb
# frozen_string_literal: true

module ForemanPasswordstate
  module HostsControllerExtensions
    extend ActiveSupport::Concern

    prepended do
      before_action :find_resource_with_passwordstate, only: %i[passwordstate_passwords_tab_selected]

      alias_method :find_resource_with_passwordstate, :find_resource
    end

    def update
      ret = super

      return ret unless host_params.dig(:passwordstate_facet_attributes, :passwordstate_server_id).empty?

      remove_passwordstate_facet

      ret
    end

    def passwordstate_server_selected
      object = @host || item_object
      passwordstate_facet = object.ensure_passwordstate_facet(save: false, **host_params[:passwordstate_facet_attributes])

      render partial: 'foreman_passwordstate/host_password_choice', locals: { item: passwordstate_facet }
    end

    def passwordstate_passwords_tab_selected
      render partial: 'foreman_passwordstate/passwords_tab_pane_content'
    rescue ActionView::Template::Error => e
      process_ajax_error e, 'fetch managed passwords'
    end

    private

    def remove_passwordstate_facet
      return unless @host.passwordstate_facet

      @host.remove_passwordstate_passwords!
      @host.passwordstate_facet.destroy
      @host.update passwordstate_facet_id: nil
    rescue StandardError => e
      logger.error "Failed to remove passwordstate facet, #{e.class}: #{e} - #{e.backtrace}"
    end

    def action_permission
      case params[:action]
      when 'passwordstate_passwords_tab_selected'
        :view
      when 'passwordstate_server_selected'
        :edit
      else
        super
      end
    end
  end
end

app/views/foreman_passwordstate/_host_password_choice.html.erb
<%-
  item = %w[hosts discovered_hosts].include?(controller_name) ? @host : @hostgroup
  facet = item&.passwordstate_facet

  inherited = false
  if !item&.persisted?
    hostgroup = @hostgroup || @host&.hostgroup
    inherited = facet.nil?
    inherited ||= true if hostgroup&.inherited_facet_attributes(Facets.registered_facets[:passwordstate_facet])&.any?

    facet ||= item&.build_passwordstate_facet(hostgroup.inherited_facet_attributes(Facets.registered_facets[:passwordstate_facet])) if inherited && hostgroup
  end
  inherited ||= true if facet.nil?
-%>

<%= fields_for item  do |f| %>
<%= f.fields_for 'passwordstate_facet_attributes' do |f| %>
  <%-
    server = facet&.passwordstate_server
    lists = []
    list = nil

    if server
      begin
        lists = server.password_lists&.map do |list|
          [ list.password_list_id, "#{list.password_list} - #{list.full_path(unix: true)}" ]
        end
        list = facet&.password_list rescue OpenStruct.new(password_list_id: facet&.password_list_id) if facet&.password_list_id
      rescue StandardError => e
        mess=e.to_s.tr("\n","½")
        Rails.logger.error "Failed to get Passwordstate password lists; #{e.class}: #{mess}"
        list = OpenStruct.new(password_list_id: facet&.password_list_id)
        lists << [ list.password_list_id, "Unknown List #{list} - #{e.class}: #{e}" ] if list.password_list_id
      end
    end
  -%>
  <div id="passwordstate_list_select" style="<%= lists.empty? && 'display:none;' || '' %>">
  <%= select_f f, :password_list_id, lists, :first, :last,
    { selected: list&.password_list_id,
      disable_button: _(HostsAndHostgroupsHelper::INHERIT_TEXT),
      disable_button_enabled: inherited
    },
    { disabled: lists.empty?,
      help_inline: :indicator,
      label: _('Password List'),
      onchange: 'update_passwordstate_list(this);'
    }
  %>
  </div>
<% end -%>
<% end -%>

app/views/foreman_passwordstate/_host_server_selection.html.erb
<%-
  item = %w[hosts discovered_hosts].include?(controller_name) ? @host : @hostgroup
  facet = item&.passwordstate_facet

  inherited = false
  if !item&.persisted?
    hostgroup = @hostgroup || @host&.hostgroup
    inherited = facet.nil?
    inherited ||= true if hostgroup&.inherited_facet_attributes(Facets.registered_facets[:passwordstate_facet])&.any?

    facet ||= item&.build_passwordstate_facet(hostgroup.inherited_facet_attributes(Facets.registered_facets[:passwordstate_facet])) if inherited && hostgroup
  end
  inherited ||= true if facet.nil?

  servers = PasswordstateServer.all.map do |server|
    name = "#{server.name} - #{server.url}"
    name += " (not available)" unless server.test_connection
    [ server.id, name ]
  end
-%>

<%= javascript 'foreman_passwordstate/host_edit_extensions.js' %>

<%= fields_for item do |f| %>
<%= f.fields_for 'passwordstate_facet_attributes' do |f| %>
  <%= select_f f, :passwordstate_server_id, servers, :first, :last,
    { include_blank: true,
      selected: facet&.passwordstate_server_id,
      disable_button: _(HostsAndHostgroupsHelper::INHERIT_TEXT),
      disable_button_enabled: inherited,
    },
    { help_inline: :indicator,
      label: _('Passwordstate Server'),
      label_help: _("<b>NB</b>: Selecting a Passwordstate server will replace ALL password handling<br/>Resetting this option will clear ALL passwords"),
      label_help_options: { data: { placement: 'top' } },
      onchange: 'update_passwordstate_server(this);',
      'data-url': url_for(action: :passwordstate_server_selected, only_path: true),
      'data-type': controller_name.singularize
    }
  %>
<% end -%>
<% end -%>

app/views/foreman_passwordstate/_passwords_tab.html.erb
<%- if @host.passwordstate_facet -%>
<%= javascript 'foreman_passwordstate/host_show_extensions.js' %>
<li><a href="#passwords" data-toggle="tab" onclick="trigger_delayed_ajax('#passwords')"><%= _("Managed Passwords") %></a></li>
<%- end -%>

app/views/foreman_passwordstate/_passwords_tab_pane.html.erb
<%- if @host.passwordstate_facet -%>
<div class="tab-pane" id="passwords" data-delayed-ajax-url="<%= passwordstate_passwords_tab_selected_host_path(@host) %>">
  <%= spinner(_('Loading password information ...')) %>
</div>
<%- end -%>

app/views/foreman_passwordstate/_passwords_tab_pane_content.html.erb
<h2>Managed passwords</h2>
<%-
all_passwords = @host.send :passwordstate_passwords

groups = all_passwords.group_by { |p| p.password_list_id.to_i }
groups.each do |id, passwords|
  pwlist = @host.passwordstate_server.password_lists.get(id)
-%>
<table class="<%= table_css_classes %>">
  <thead>
    <tr>
      <th colspan="2"><a href="<%= @host.passwordstate_server.get_list_url(pwlist) %>" title="<%= pwlist.description %>" target="_blank"><%= pwlist.full_path %>&nbsp;<i class="fa fa-external-link"></i></a></th>
    </tr>
  </thead>
  <tbody>
<%- passwords.each do |pw| -%>
    <tr>
      <td title="<%= pw.notes || pw.description.split('|').first.strip %>"><a href="<%= @host.passwordstate_server.get_password_url(pw) %>" target="_blank"><%= pw.user_name %>&nbsp;<i class="fa fa-external-link"></i></a></td>
<%- if pw.expiry_date -%>
      <td colspan="2" title="<%= pw.expiry_date %>">
<%-
expired = Time.now > pw.expiry_date
diff = (Time.now - pw.expiry_date).abs
expiry_near = diff < 30 * 24 * 60 * 60

if expiry_near
  str = _('Expires %s') unless expired
  str = _('Expired %s') if expired
-%>
<%= str % date_time_relative_value(pw.expiry_date) %>
<%-
else
  str = _('Expires on %s') unless expired
  str = _('Expired on %s') if expired
-%>
<%= str % date_time_absolute_value(pw.expiry_date) %>
<%-
end
-%>
      </td>
<%- end -%>
    </tr>
<%- end -%>
  </tbody>
</table>
<%- end -%>