config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    scope '(:apiv)', module: :v2,
                     defaults: { apiv: 'v2' },
                     apiv: /v1|v2/,
                     constraints: ApiConstraints.new(version: 2) do
      get 'passwords/:user', to: 'passwords#acquire'
      delete 'passwords/:user', to: 'passwords#release'
    end
  end

  scope '/foreman_passwordstate' do
    constraints(id: %r{[^/]+}) do
      resources :passwordstate_servers do
        collection do
          get 'auto_complete_search'
          post 'test_connection'
        end
        member do
          get 'folders'
          get 'password_lists'
        end
      end
    end
  end

  constraints(id: %r{[^/]+}) do
    resources :hostgroups, only: [] do
      collection do
        post 'passwordstate_server_selected'
      end
    end
    resources :hosts, only: [] do
      collection do
        post 'passwordstate_server_selected'
      end
      member do
        get 'passwordstate_passwords_tab_selected'
      end
    end
    resources :discovered_hosts, only: [] do
      collection do
        post 'passwordstate_server_selected'
      end
    end
  end
end

app/models/passwordstate_server.rb
# frozen_string_literal: true

class PasswordstateServer < ApplicationRecord
  include ForemanPasswordstate::PasswordstateCaching
  include Taxonomix
  include Encryptable

  extend FriendlyId
  friendly_id :name
  include Parameterizable::ByIdName
  encrypts :password

  validates_lengths_from_database

  audited except: %i[password]

  before_destroy EnsureNotUsedBy.new :hosts
  has_many :passwordstate_host_facets,
           class_name: '::ForemanPasswordstate::PasswordstateHostFacet',
           dependent: :destroy,
           inverse_of: :passwordstate_server
  has_many :passwordstate_hostgroup_facets,
           class_name: '::ForemanPasswordstate::PasswordstateHostgroupFacet',
           dependent: :destroy,
           inverse_of: :passwordstate_server

  has_many :hosts,
           class_name: '::Host::Managed',
           dependent: :nullify,
           inverse_of: :passwordstate_server,
           through: :passwordstate_host_facets
  has_many :hostgroups,
           class_name: '::Hostgroup',
           dependent: :nullify,
           inverse_of: :passwordstate_server,
           through: :passwordstate_hostgroup_facets

  validates :name, presence: true, uniqueness: true
  validates :url, presence: true
  validates :api_type, presence: true

  validate :validate_api_configuration

  scoped_search on: :name
  default_scope -> { order('passwordstate_servers.name') }

  delegate :version, :passwords, to: :client

  def test_connection(**_)
    return false unless url

    client.valid?
  rescue StandardError
    false
  end

  def folders
    data = cache.cache(:folders) do
      return client.folders.map(&:attributes) if api_type.to_sym == :winapi

      client.folders.tap do |folders|
        folders.instance_eval <<-CODE, __FILE__, __LINE__ + 1
        def lazy_load
          load []
        end
        CODE
      end.map(&:attributes)
    end
    client.folders.load data.map { |d| client.folders.new d }
  end

  def hosts
    data = cache.cache(:hosts) do
      client.hosts.map(&:attributes)
    end
    client.hosts.load data.map { |d| client.hosts.new d }
  end

  def password_lists
    data = cache.cache(:password_lists) do
      return client.password_lists.map(&:attributes) if api_type.to_sym == :winapi

      # Only handle a single password list if using API keys
      client.password_lists.tap do |list|
        list.instance_eval <<-CODE, __FILE__, __LINE__ + 1
        def lazy_load
          load [get(#{user}, _force: true)] # load [get(15, _force: true)]
        rescue StandardError => ex
          client.logger.error "Failed to load entries for password list - \#{ex.class}: \#{ex}"
          load []
        end
        CODE
      end.map(&:attributes)
    end
    client.password_lists.load data.map { |d| client.password_lists.new d }
  end

  def get_list_url(pwlist)
    URI.join client.server_url, "plid=#{pwlist.password_list_id}"
  end

  def get_password_url(password)
    URI.join client.server_url, "pid=#{password.password_id}"
  end

  private

  def client
    require 'passwordstate'

    @client ||= Passwordstate::Client.new(url, api_type: api_type.to_sym, open_timeout: 5, timeout: 10).tap do |cl|
      if api_type.to_sym == :api
        cl.auth_data = { apikey: password }
      else
        domain = nil
        username = user

        if (separator = ['/', '\\', '@'].find { |sep| user.include? sep }) && user.count(separator) == 1
          domain, username = user.split(separator)
          domain, username = username, domain if separator == '@'
        end

        cl.auth_data = { username: username, password: password }
        cl.auth_data[:domain] = domain if domain
      end
    end
  end

  def validate_api_configuration
    errors.add(:api_type, 'must be valid') unless %i[winapi api].include?(api_type.to_sym)

    if api_type.to_sym == :api
      errors.add(:password, 'must provide a valid API Key') unless password.size == 32
      errors.add(:user, 'must be a valid Password List ID') unless user.to_i.to_s == user
    else
      errors.add(:user, 'must provide a username') if user.empty?
      errors.add(:password, 'must provide a password') if password.empty?
    end
  end
end

app/controllers/concerns/foreman/controller/parameters/passwordstate_server.rb
# frozen_string_literal: true

module Foreman::Controller::Parameters::PasswordstateServer
  extend ActiveSupport::Concern

  class_methods do
    def passwordstate_server_params_filter
      Foreman::ParameterFilter.new(::PasswordstateServer).tap do |filter|
        filter.permit :name,
                      :description,
                      :url,
                      :api_type,
                      :user,
                      :password,
                      :apikey
      end
    end
  end

  def passwordstate_server_params
    self.class.passwordstate_server_params_filter.filter_params(params, parameter_filter_context, :passwordstate_server)
  end
end

app/controllers/passwordstate_servers_controller.rb
# frozen_string_literal: true

class PasswordstateServersController < ApplicationController
  include Foreman::Controller::AutoCompleteSearch
  include Foreman::Controller::Parameters::PasswordstateServer

  before_action :find_server, except: %i[index new create test_connection]

  def index
    @passwordstate_servers = resource_base_search_and_page
  end

  def show; end

  def new
    @passwordstate_server = PasswordstateServer.new
  end

  def edit; end

  def create
    @passwordstate_server = PasswordstateServer.new(passwordstate_server_params)
    if @passwordstate_server.save
      process_success success_redirect: passwordstate_server_path(@passwordstate_server)
    else
      process_error
    end
  end

  def update
    if @passwordstate_server.update(passwordstate_server_params)
      process_success
    else
      process_error
    end
  end

  def destroy
    if @passwordstate_server.destroy
      process_success
    else
      process_error
    end
  end

  def test_connection
    # passwordstate_id is posted from AJAX function. passwordstate_id is nil if new
    if params[:passwordstate_id].present?
      @passwordstate_server = PasswordstateServer.authorized(:edit_passwordstate_server).find(params[:passwordstate_id])
      @passwordstate_server.attributes = passwordstate_server_params.reject { |k, v| k == :password && v.blank? }
    else
      @passwordstate_server = PasswordstateServer.new(passwordstate_server_params)
    end

    if @passwordstate_server.test_connection
      head 200
    else
      head 422
    end
  end

  def folders
    @passwordstate_server.folders
  end

  def password_lists
    @passwordstate_server.password_lists
  end

  private

  def find_server
    @passwordstate_server = PasswordstateServer.find(params[:id])
  end
end

app/views/passwordstate_servers/_form.html.erb
<%= form_for @passwordstate_server, :url => (@passwordstate_server.new_record? ? passwordstate_servers_path : passwordstate_server_path(name: @passwordstate_server.name)), html: {data: {id: @passwordstate_server.try(:id)}} do |f| %>
  <%= base_errors_for @passwordstate_server %>
  <ul class="nav nav-tabs" data-tabs="tabs">
    <li class="active"><a href="#primary" data-toggle="tab"><%= _('Server') %></a></li>
    <% if show_location_tab? && false %>
      <li><a href="#locations" data-toggle="tab"><%= _('Locations') %></a></li>
    <% end %>
    <% if show_organization_tab? && false %>
      <li><a href="#organizations" data-toggle="tab"><%= _('Organizations') %></a></li>
    <% end %>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="primary">
      <%= text_f f, :name %>
      <%= text_f f, :url, placeholder: 'https://passwordstate.example.com' %>
      <%= textarea_f f, :description, :rows => 3 %>
      <%= selectable_f f, :api_type, [['Username + Password', :winapi],['API Key', :api]], { selected: @passwordstate_server.api_type }, label: _('Authorization Method'), required: true, size: 'col-md-4' %>
      <%= hidden_field_tag :redirect, params[:redirect] %>

      <fieldset id="passwordstate_winapi" class="authorization_form" style="display: none;">
        <%= text_f f, :user, required: true %>
        <%= password_f f, :password, required: true %>
      </fieldset>
      <fieldset id="passwordstate_api" class="authorization_form" style="display: none;">
        <%= password_f f, :password, label: _('API Key'), required: true %>
        <%= text_f f, :user, label: _('Password List ID'), required: true %>
      </fieldset>

      <%= link_to_function _("Test Connection"), "testConnection(this)", id: 'test_connection_button', class: "btn #{@passwordstate_server.test_connection.is_a?(FalseClass) ? "btn-default" : "btn-success"}", :'data-url' => test_connection_passwordstate_servers_path %>
    </div>
    <%#= render 'taxonomies/loc_org_tabs', :f => f, :obj => @passwordstate_server %>
  </div>

  <%= submit_or_cancel f %>
<% end %>

app/views/passwordstate_servers/edit.html.erb
<%= javascript 'foreman_passwordstate/passwordstate_servers' %>

<% title _('Edit Passwordstate Server %s') % @passwordstate_server.name %>

<%= render partial: 'form' %>

app/views/passwordstate_servers/index.html.erb
<% title _('Passwordstate Servers') %>
<% title_actions new_link(_('Create Passwordstate Server connection')) %>

<table class="<%= table_css_classes 'table-fixed' %>">
  <thead>
    <tr>
      <th class="col-md-6"><%= sort :name, :as => s_("Passwordstate Server|Name") %></th>
      <th><%= _('Actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @passwordstate_servers.each do |server| %>
      <tr>
        <td class="ellipsis"><%= link_to server.name, server %></td>
        <td>
          <%= action_buttons(link_to_if_authorized(_('Edit'), hash_for_edit_passwordstate_server_path(server).merge(:auth_object => server, :authorizer => authorizer)))
          #display_delete_if_authorized(hash_for_destroy_passwordstate_server_path(:id => server).merge(:auth_object => server, :authorizer => authorizer), :data => { :confirm => _("Delete %s?") % server.name })
          %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate_with_info @passwordstate_servers %>

app/views/passwordstate_servers/new.html.erb
<%= javascript 'foreman_passwordstate/passwordstate_servers' %>

<% title _('Create Passwordstate Server connection') %>

<%= render 'form' %>

app/views/passwordstate_servers/show.html.erb
<% title @passwordstate_server.name %>
<% title_actions \
  link_to_if_authorized(_('Edit'), hash_for_edit_passwordstate_server_path(@passwordstate_server).merge(:auth_object => @passwordstate_server), class: 'btn btn-default') %>
<% javascript 'foreman_passwordstate/passwordstate_servers' %>

<ul class="nav nav-tabs" data-tabs="tabs">
  <li class="active"><a href="#primary" data-toggle="tab"><%= _('Passwordstate Server') %></a></li>
  <li><a href="#folders" data-toggle="tab"><%= _('Folders') %></a></li>
  <li><a href="#password-lists" data-toggle="tab"><%= _('Password lists') %></a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="primary">
    <table class="<%= table_css_classes 'table-fixed' %>">
      <thead>
        <tr>
          <th class="col-md-1"><%= _('Property') %></th>
          <th class="col-md-11"><%= _('Value') %></th>
        </tr>
      </thead>
      <tbody>
        <%- unless @passwordstate_server.description.empty? -%>
        <tr>
          <td><%= _('Description') %></td>
          <td><%= @passwordstate_server.description %></td>
        </tr>
        <%- end -%>
        <tr>
          <td><%= _('Url') %></td>
          <td><a href="<%= @passwordstate_server.url %>"><%= @passwordstate_server.url %></a></td>
        </tr>
        <tr>
          <td><%= _('Version') %></td>
          <td><%= @passwordstate_server.version rescue 'N/A' %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="tab-pane" id="folders">
    <table class="<%= table_css_classes 'table-fixed' %>">
      <thead>
        <tr>
          <th class="col-md-1"><%= _('Name') %></th>
          <th class="col-md-2"><%= _('Path') %></th>
          <th class="col-md-9"><%= _('Description') %></th>
        </tr>
      </thead>
      <tbody>
        <%-
          begin
            #@passwordstate_server.folders
            []
          rescue
            []
          end.each do |folder|
        -%>
        <tr>
          <td><%= folder.folder_name %></td>
          <td><%= folder.full_path(true) %></td>
          <td><%= folder.description %></td>
        </tr>
      <%- end -%>
      </tbody>
    </table>
  </div>
  <div class="tab-pane" id="password-lists">
    <table class="<%= table_css_classes 'table-fixed' %>">
      <thead>
        <tr>
          <th class="col-md-2"><%= _('Name') %></th>
          <th class="col-md-3"><%= _('Full Path') %></th>
          <th class="col-md-7"><%= _('Description') %></th>
        </tr>
      </thead>
      <tbody>
      <%- @passwordstate_server.password_lists.each do |list| -%>
        <tr>
          <td><%= list.password_list %></td>
          <td><a href="<%= @passwordstate_server.get_list_url(list)  %>" target="_blank"><%= list.full_path(unix: true) %></a></td>
          <td><%= list.description %></td>
        </tr>
      <%- end -%>
      </tbody>
    </table>
  </div>
</div>